{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo.py:10: AssertionError"}, "description": "this test fails", "start": 1615647149057, "stop": 1615647149057, "uuid": "1409743f-4fe2-4462-a3eb-69038a8f6e6b", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "9492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}